[package]
name = "octtree_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib_minya = { path = "../lib_minya" }
image = "0.24.2"
cgmath = { version = "0.18.0", features = ["swizzle"] }